### ISSUE TITLE
This isn't an issue but I've a question..

### ISSUE THREAD

**Issue by coolhandle01** [hit9/node-block-queue#1]
My question is, `if (!condition)`, does my function stay in the queue and get called again?

```
q.push(function(done) {
  if (!condition) {
      // not ready to work
  } else {
   // ready to work
    done();
  }
});
```

**Comment by djmitche** [comment]
No, it will be counted as still executing, but will never do anything.  Don't do that :)

**Comment by coolhandle01** [comment]
Ah. `while(1)`.. Please close this lol
